version: "3.9"  

services:

  go_app:
    build:
      context: ./service_1
      dockerfile: Dockerfile
    container_name: go-app
    expose:
      - "8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  python_app:
    build:
      context: ./service_2
      dockerfile: Dockerfile
    container_name: python-app
    expose:
      - "8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "82:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      go_app:
        condition: service_healthy
      python_app:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
